/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import com.sun.media.jai.widget.DisplayJAI;
import control.Binarization;
import control.GraphExtractor;
import control.Grayscale;
import control.HangulImageController;
import control.PreClassification;
import control.GraphMatcher;
import control.Skeletonization;
import control.Training;
import entity.Graph;
import entity.HangulImage;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Herbita
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private HangulImageController hangulImageController;
    private HangulImage hangulImage;
    private DisplayJAI displayJAI;
    private Grayscale grayscale;
    private Binarization binarization;
    private Skeletonization thinner;
    private PreClassification preClassification;
    private GraphExtractor graphExtractor;
    private Training training;
    private GraphMatcher recognizer;
    private Graph graph[];
    private String fileName;
    
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new javax.swing.JPanel();
        openImageBttn = new javax.swing.JButton();
        recognizeBttn = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel1.setBackground(new java.awt.Color(192, 192, 192));
        imagePanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));
        imagePanel1.setPreferredSize(new java.awt.Dimension(290, 290));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        openImageBttn.setText("Open Image");
        openImageBttn.setPreferredSize(new java.awt.Dimension(100, 35));
        openImageBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openImageBttnMouseClicked(evt);
            }
        });
        openImageBttn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                openImageBttnKeyTyped(evt);
            }
        });

        recognizeBttn.setText("Recognize");
        recognizeBttn.setPreferredSize(new java.awt.Dimension(111, 35));
        recognizeBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recognizeBttnMouseClicked(evt);
            }
        });

        imagePanel.setBackground(new java.awt.Color(192, 192, 192));
        imagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));
        imagePanel.setPreferredSize(new java.awt.Dimension(290, 290));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recognizeBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openImageBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openImageBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recognizeBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayImage(JPanel panel){
        displayJAI = new DisplayJAI(hangulImage.getImage());
        panel.setLayout(new BorderLayout());
        displayJAI.setBackground(new Color(201, 201, 201));
        panel.add(displayJAI,BorderLayout.CENTER);
        validate();
    }
    
    private void openImageBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openImageBttnMouseClicked
        hangulImageController = new HangulImageController();
        hangulImage = hangulImageController.open();
        fileName = hangulImageController.getFileName();
        displayImage(imagePanel);
    }//GEN-LAST:event_openImageBttnMouseClicked

    private void recognizeBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recognizeBttnMouseClicked
        grayscale = new Grayscale(hangulImage);
        binarization = new Binarization(hangulImage);
        thinner = new Skeletonization(hangulImage);
        hangulImageController.refreshImage();
        graphExtractor = new GraphExtractor(hangulImage);
        graph = graphExtractor.getGraph();
        //training = new Training(fileName, graph);
        recognizer = new GraphMatcher(graph);
        //hangulGraph = graphExtractor.getHangulGraph();
        //recognizer = new GraphMatcher(hangulGraph);
        //imageFileController.refreshImage();
        displayImage(imagePanel1);
    }//GEN-LAST:event_recognizeBttnMouseClicked

    private void openImageBttnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_openImageBttnKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_openImageBttnKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel imagePanel1;
    private javax.swing.JButton openImageBttn;
    private javax.swing.JButton recognizeBttn;
    // End of variables declaration//GEN-END:variables
}
